#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-http-cookie
Version  : 1.0.2
Release  : 4
URL      : https://rubygems.org/downloads/http-cookie-1.0.2.gem
Source0  : https://rubygems.org/downloads/http-cookie-1.0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-test-unit

%description
# HTTP::Cookie
HTTP::Cookie is a ruby library to handle HTTP cookies in a way both
compliant with RFCs and compatible with today's major browsers.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n http-cookie-1.0.2
gem spec %{SOURCE0} -l --ruby > rubygem-http-cookie.gemspec

%build
gem build rubygem-http-cookie.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
http-cookie-1.0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/http-cookie-1.0.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/http-cookie.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http-cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie/ruby_compat.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie/scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/abstract_saver.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/abstract_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/cookiestxt_saver.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/hash_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/mozilla_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/yaml_saver.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/test/mechanize.yml
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/test/simplecov_start.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/test/test_http_cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-cookie-1.0.2/test/test_http_cookie_jar.rb
/usr/lib64/ruby/gems/2.3.0/specifications/http-cookie-1.0.2.gemspec
