#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-http-cookie
Version  : 1.0.2
Release  : 3
URL      : https://rubygems.org/downloads/http-cookie-1.0.2.gem
Source0  : https://rubygems.org/downloads/http-cookie-1.0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-test-unit

%description
# HTTP::Cookie
HTTP::Cookie is a ruby library to handle HTTP cookies in a way both
compliant with RFCs and compatible with today's major browsers.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n http-cookie-1.0.2
gem spec %{SOURCE0} -l --ruby > rubygem-http-cookie.gemspec

%build
gem build rubygem-http-cookie.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
http-cookie-1.0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/http-cookie-1.0.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/Array/select%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/Array/sort_by%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/cdesc-Scanner.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/parse_cookie_date-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/quote-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_dquoted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_name_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_set_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/scan_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/skip_wsp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/Scanner/tuple_to_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/acceptable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/acceptable_from_uri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/accessed_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/cdesc-Cookie.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/cookie_value-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/cookie_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/cookie_value_to_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/created_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/domain%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/domain_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/dot_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/encode_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expire%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expired%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expires%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expires-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expires_at%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/expires_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/for_domain%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/for_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/httponly%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/httponly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/init_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/max_age%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/max_age-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/name%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/origin%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/origin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/path%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/path_match%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/secure%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/secure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/session%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/set_cookie_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/to_yaml_properties-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/valid_for_uri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/value%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/Cookie/yaml_initialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/cdesc-AbstractSaver.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/implementation-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractSaver/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/cdesc-AbstractStore.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/implementation-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/AbstractStore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/cdesc-CookiestxtSaver.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/cookie_to_record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/parse_record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/CookiestxtSaver/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/cdesc-HashStore.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/HashStore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/Database/cdesc-Database.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/cdesc-MozillaStore.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/closed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/create_table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/db_add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/db_delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/db_prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/schema_version%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/schema_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/MozillaStore/upgrade_database-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/YAMLSaver/cdesc-YAMLSaver.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/YAMLSaver/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/YAMLSaver/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/YAMLSaver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/YAMLSaver/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/cdesc-CookieJar.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/get_impl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/CookieJar/store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/HTTP/cdesc-HTTP.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/Hash/try_convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/String/try_convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/http-cookie-1.0.2/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/http-cookie.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http-cookie.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie/ruby_compat.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie/scanner.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/abstract_saver.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/abstract_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/cookiestxt_saver.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/hash_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/mozilla_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie_jar/yaml_saver.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/test/mechanize.yml
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/test/simplecov_start.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/test/test_http_cookie.rb
/usr/lib64/ruby/gems/2.2.0/gems/http-cookie-1.0.2/test/test_http_cookie_jar.rb
/usr/lib64/ruby/gems/2.2.0/specifications/http-cookie-1.0.2.gemspec
